// Generated by https://quicktype.io

export interface ActualizarUsuarioResponse {
  ok:      boolean;
  usuario: Usuario;
}

export interface Usuario {
  _id:    string;
  nombre: string;
  email:  string;
  role:   string;
  google: boolean;
  img:    string;
}
