// Generated by https://quicktype.io

import { HospitalUsuario } from "../models/hospital.model";
import { Medico } from "../models/medico";

export interface BusquedaTodo {
  ok:                boolean;
  paramteroBusqueda: string;
  usuarios:          Usuario[];
  medicos:           Medico[];
  hospitales:        HospitalUsuario[];
}


export interface Usuario {
  _id:    string;
  nombre: string;
  email:  string;
  img?:   string;
  role:   Role;
  google: boolean;
}

export enum Role {
  AdminRole = "ADMIN_ROLE",
  UserRole = "USER_ROLE",
}
