// Generated by https://quicktype.io

export interface CrearMedicoResponse {
  ok:      boolean;
  message: string;
  medico:  Medico;
}

export interface Medico {
  nombre:   string;
  usuario:  string;
  hospital: string;
  _id:      string;
}
