// Generated by https://quicktype.io

export interface CrearHospitalResponse {
  ok:       boolean;
  message:  string;
  hospital: Hospital;
}

export interface Hospital {
  nombre:  string;
  usuario: string;
  _id:     string;
}
