// Generated by https://quicktype.io

export interface CrearUsuarioResponse {
  ok:      boolean;
  message: string;
  usuario: Usuario;
  token:   string;
}

export interface Usuario {
  nombre: string;
  email:  string;
  role:   string;
  google: boolean;
  _id:    string;
}
