// Generated by https://quicktype.io

export interface GetMedicoIDResponse {
  ok:     boolean;
  medico: Medico;
}

export interface Medico {
  _id:      string;
  nombre:   string;
  usuario:  Usuario;
  hospital: Hospital;
  img:      string;
}

export interface Hospital {
  _id:    string;
  nombre: string;
}

export interface Usuario {
  _id:    string;
  nombre: string;
  email:  string;
  img:    string;
}
