// Generated by https://quicktype.io

import { Hospital } from "../models/hospital.model";
import { MedicoUser } from "../models/medico";

export interface GetMedicosResponse {
  ok:      boolean;
  message: string;
  medicos: Medico[];
}

export interface Medico {
  _id:      string;
  nombre:   string;
  usuario?:  MedicoUser;
  hospital?: Hospital;
  img?:     string;
}


export interface Usuario {
  _id:    string;
  nombre: string;
  email:  string;
  img:    string;
}
