// Generated by https://quicktype.io

export interface RenewTokenResponse {
  ok:    boolean;
  uid:   string;
  token: string;
  menu:string;
  usuario: Usuario
}


export interface Usuario {

    _id: string;
    nombre: string ;
    email: string;
    img: string;
    role: string;
    google: false;

}
